version: '3'

services:
  rethinkdb:
    image: rethinkdb:2.4-buster-slim
    ports:
      - 28015:28015
      - 8080:8080
  adapter:
    build: .
    depends_on:
      - rethinkdb
    environment:
      - RUBY_ENV=test
      - RETHINKDB_HOST=rethinkdb
    volumes:
      - .:/adapter
